name: Build & Deploy

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
    - name: npm install polymer-cli
      run: npm install polymer-cli
    - name: web-component-designer upgrade
      run: npm i git+https://git@github.com/node-projects/web-component-designer.git
    - name: Compile web-component-designer
      run: |
        cd ./node_modules/@node-projects/web-component-designer
        npm install
        npx tsc
    - name: Typescript
      run: npx tsc
    - name: Polymer
      run: npx polymer build
    - name: Copy css and rest
      run: |
        npm i copyfiles
        npx copyfiles ./node_modules/**/*.css build/default
        npx copyfiles ./node_modules/**/*.json build/default
        npx copyfiles ./*.json build/default
        npx copyfiles ./node_modules/ace-builds/**/*.js build/default
        npx copyfiles ./node_modules/mobile-drag-drop/**/*.js build/default
        npx copyfiles ./node_modules/@node-projects/web-component-designer/dist/polyfill/*.js build/default
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/default # The folder the action should deploy.
