name: Build & Deploy

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
    - name: npm install polymer-cli
      run: npm install polymer-cli
    - name: web-component-designer upgrade
      run: npm i git+https://git@github.com/node-projects/web-component-designer.git
    - name: Typescript
      run: npx tsc build
    - name: Polymer
      run: npx polymer build
    - name: npm install polymer-cli
      run: npm install polymer-cli
